spring:
  data:
    cassandra:
      port: 9042	
#      contact-points: cassandra
      contact-points: 192.168.16.129
      keyspace-name: cs443
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1
